addons:
  apt:
    packages:
    - lua5.2
    - liblua5.2-dev
language: python
python:
- '2.7'
- '3.2'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
- pypy
- pypy3
install:
- pip install .
- if [[ "$TRAVIS_PYTHON_VERSION" =~ ^(2.7|3.4)$ ]]; then pip install .[lua]; fi
# Add 3.2, 3.3, 3.5, and 3.6 when https://github.com/travis-ci/travis-ci/issues/8217 is fixed
script: python setup.py nosetests
deploy:
  provider: pypi
  user: github-ll
  password:
    secure: WZNNslmr6ELiasA6IhO9QDQ/g7758WjezVLqC3Ebo3EgAsUOFeCvtqODf3U8czz4UxORrVL7xWN/lUEOCG/ImDoXa9W27h8kl3D0pP9s8FDNngZspB5c3xhZhQesiqB6n8Fyi2dLic9QYUUIgquo2w+w/r5rRHvplI9OVbIGuVM=
  on:
    tags: true
    repo: locationlabs/mockredis
